// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrE66vq172oqSXJH8tF0HDLbvuFTKskBg',
    appId: '1:581908058721:web:a1636464838b47c1a95020',
    messagingSenderId: '581908058721',
    projectId: 'sprout-b8917',
    authDomain: 'sprout-b8917.firebaseapp.com',
    storageBucket: 'sprout-b8917.firebasestorage.app',
    measurementId: 'G-R096T5EGFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6WJTDN1jIG2oSC6DP1WvoAmTRWSzbQ6c',
    appId: '1:581908058721:android:c30be5ca362c43d2a95020',
    messagingSenderId: '581908058721',
    projectId: 'sprout-b8917',
    storageBucket: 'sprout-b8917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQG-dINrhDuZxc8RgWRc9MsSsvxupVNCQ',
    appId: '1:581908058721:ios:77ac883901244cc1a95020',
    messagingSenderId: '581908058721',
    projectId: 'sprout-b8917',
    storageBucket: 'sprout-b8917.firebasestorage.app',
    iosBundleId: 'com.example.studyPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQG-dINrhDuZxc8RgWRc9MsSsvxupVNCQ',
    appId: '1:581908058721:ios:77ac883901244cc1a95020',
    messagingSenderId: '581908058721',
    projectId: 'sprout-b8917',
    storageBucket: 'sprout-b8917.firebasestorage.app',
    iosBundleId: 'com.example.studyPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrE66vq172oqSXJH8tF0HDLbvuFTKskBg',
    appId: '1:581908058721:web:10e0b834c2d66e2aa95020',
    messagingSenderId: '581908058721',
    projectId: 'sprout-b8917',
    authDomain: 'sprout-b8917.firebaseapp.com',
    storageBucket: 'sprout-b8917.firebasestorage.app',
    measurementId: 'G-QPG1JCYWCB',
  );
}
